### ISSUE TITLE
nodeagent crash looping on configuration update via aws cli update-addon

### ISSUE THREAD

**Issue by litewhatever** [aws/aws-network-policy-agent#97]
Hello

I am running EKS cluster with VPC CNI `v1.5.1` which has nodeagent `v1.0.4-eksbuild.1`

When trying to overwrite existing configuration with empty json block nodeagent starts to crash:
```
{"level":"info","ts":"2023-10-16T11:00:53.366Z","caller":"runtime/asm_amd64.s:1598","msg":"version","GitVersion":"","GitCommit":"","BuildDate":""}
2023-10-16 11:00:53.369241842 +0000 UTC Logger.check error: failed to get caller
2023-10-16 11:00:53.369301877 +0000 UTC Logger.check error: failed to get caller
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x28 pc=0x5631030676a7]

goroutine 88 [running]:
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile.func1()
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.15.1/pkg/internal/controller/controller.go:115 +0x1fa
panic({0x563103c97980, 0x563105082fc0})
	/root/sdk/go1.20.4/src/runtime/panic.go:884 +0x213
github.com/aws/aws-network-policy-agent/controllers.(*PolicyEndpointsReconciler).configureeBPFProbes(0xc000562a80, {0x563103ffc100, 0xc0005e8a80}, {0xc000048f48, 0x17}, {0xc00065c980?, 0x1, 0xc0005ec600?}, {0xc000334800, 0x6, ...}, ...)
	/workspace/controllers/policyendpoints_controller.go:258 +0x3e7
github.com/aws/aws-network-policy-agent/controllers.(*PolicyEndpointsReconciler).reconcilePolicyEndpoint(0xc000562a80, {0x563103ffc100, 0xc0005e8a80}, 0xc000804d00)
	/workspace/controllers/policyendpoints_controller.go:232 +0x7b1
github.com/aws/aws-network-policy-agent/controllers.(*PolicyEndpointsReconciler).reconcile(0xc000562a80, {0x563103ffc100, 0xc0005e8a80}, {{{0xc0004c1dc6, 0x5}, {0xc0005ec600, 0x26}}})
	/workspace/controllers/policyendpoints_controller.go:149 +0x24c
github.com/aws/aws-network-policy-agent/controllers.(*PolicyEndpointsReconciler).Reconcile(0xc000562a80, {0x563103ffc100, 0xc0005e8a80}, {{{0xc0004c1dc6, 0x5}, {0xc0005ec600, 0x26}}})
	/workspace/controllers/policyendpoints_controller.go:130 +0x11f
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile(0x563103ffc100?, {0x563103ffc100?, 0xc0005e8a80?}, {{{0xc0004c1dc6?, 0x563103b2f000?}, {0xc0005ec600?, 0x563103fe8ee8?}}})
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.15.1/pkg/internal/controller/controller.go:118 +0xc8
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler(0xc000740820, {0x563103ffc058, 0xc00073bcc0}, {0x563103d83200?, 0xc000736080?})
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.15.1/pkg/internal/controller/controller.go:314 +0x377
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem(0xc000740820, {0x563103ffc058, 0xc00073bcc0})
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.15.1/pkg/internal/controller/controller.go:265 +0x1d9
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2()
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.15.1/pkg/internal/controller/controller.go:226 +0x85
created by sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.15.1/pkg/internal/controller/controller.go:222 +0x587
```

To reproduce:

1. Install VPC CNI addon
```
aws eks create-addon \
  --cluster-name <eks cluster> \
  --addon-name vpc-cni \
  --addon-version v1.15.1-eksbuild.1 \
  --service-account-role-arn <rolearn> \
  --configuration-values '{}'
```

2. Enable network policies
```
aws eks update-addon \
  --cluster-name <eks cluster> \
  --addon-name vpc-cni \
  --service-account-role-arn <rolearn> \
  --resolve-conflicts OVERWRITE --configuration-values '{"enableNetworkPolicy": "true", "nodeAgent": {"enableCloudWatchLogs": "true"}}'
```

3. Update configuration with empty block to disable network policy
```
aws eks update-addon \
  --cluster-name <eks cluster> \
  --addon-name vpc-cni \
  --service-account-role-arn <rolearn> \
  --resolve-conflicts OVERWRITE --configuration-values '{}'
```

**Comment by achevuru** [comment]
It appears that you still have active Network policies and custom CRD resources (`policyEndpoints`) in your cluster. Please delete the stale resources before you disable NP.

**Comment by litewhatever** [comment]
Note that those policies/resources were there before enabling NP (step 1) and this didn't cause nodeagent to crash loop.

**Comment by treyhyde** [comment]
This last update caused a tremendous amount of pain in our dev cluster this morning.  After applying network policy to 1.15.1, no pods would start and aws-node hit the crashloop as above.  Rolling back to network-policy off and 1.15.0 didn't fix any issues with existing nodes.  Only new nodes would work after that.

**Comment by achevuru** [comment]
@litewhatever Issue is not with `NetworkPolicies` resources but instead the issue here is with `PolicyEndpoint` resources that Network Policy controller creates after we enable the feature on the cluster via VPC CNI. If you're disabling Network Policy feature in VPC CNI and/or want to move to a different Network Policy solution we need to delete the Network Policies that VPC CNI and the Network Policy controller already reconciled on and this will give the components a chance to go remove the BPF probes attached to the pods and revert the pod behavior to default allow. We shouldn't disable the feature with active `PolicyEndpoint` resources as this will leave the pods with active policies in a bad state and in the above scenario we are trying to disable the feature but there are active resources to reconcile on. We wanted to fail hard in this scenario to avoid running in to issues with stale probes if the feature is enabled again on the same cluster (and as called out earlier the pods will still have stale probes attached).

You can force delete all the `PolicyEndpoint` resources as a workaround for now, although this is not recommended in general.

**Comment by litewhatever** [comment]
I see, thanks for the explanation. I will close this issue as not relevant.
